# Generated by Django 3.2.5 on 2022-03-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emergencies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyrequest',
            name='unit_type',
            field=models.CharField(choices=[('firefighter', 'firefighter'), ('medic', 'medic'), ('police', 'police')], default='police', max_length=15),
        ),
    ]
