# Generated by Django 3.2.5 on 2022-03-20 08:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emergencies', '0003_emergencyrequest_assigned_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyrequest',
            name='assigned_units',
            field=models.ManyToManyField(related_name='assigned_emergencies', to=settings.AUTH_USER_MODEL),
        ),
    ]
