# Generated by Django 3.2.5 on 2022-02-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220207_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='social_security_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
