# Generated by Django 3.2.5 on 2022-02-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_social_security_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateField(auto_now=True, verbose_name='last login'),
        ),
    ]
