# Generated by Django 3.2.5 on 2022-02-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isApproved',
            field=models.BooleanField(default=True),
        ),
    ]
