# Generated by Django 3.2.5 on 2022-03-20 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitLocation',
            fields=[
                ('unit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user')),
                ('longitude', models.DecimalField(decimal_places=16, default=32.866287, max_digits=22)),
                ('latitude', models.DecimalField(decimal_places=16, default=39.925533, max_digits=22)),
            ],
        ),
    ]
